### ISSUE TITLE
Dockerfile doesn't want to work correctly

### ISSUE THREAD

**Issue by ZenergyBryson** [haidaraM/terraform-jenkins-aws-fargate#3]
First off, thanks so much for creating this!
To clarify, the Dockerfile does all the steps (once you update RUN install-plugins to jenkins-plugins-cli), but the resulting image doesn't work with the JCASC file pushed to S3 by the Terraform project.  It throws a TON of errors around bad arguments (
I feel like there are steps missing - any chance you could update this? 

io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate : networkMode,taskrole,uniqueRemoteFSRoot,memoryReservation,templateName,assignPublicIp,platformVersion,securityGroups,subnets,executionRole,sharedMemorySize,launchType.

**Comment by haidaraM** [comment]
Hi, are you using my image or you built a new one? This is likely due to Jenkins or the plugin being updated. 

Can you try with my latest image and let me know?

**Comment by ZenergyBryson** [comment]
It all works just fine with your image on Dockerhub (tag 2.338 says it's considerably newer than "latest"), but I get a ton of errors around updating / installing extensions.
When I run the Dockerfile you included in this repo, it goes and pulls jenkins/jenkins:latest (I also tried :slim) and that doesn't work.  I would assume because there are things missing in the Dockerfile that need to be applied, or the jcasc-config file needs major changes.
Any help is appreciated!

**Comment by haidaraM** [comment]
Ok, will take a look once I have sometime. Probably need to update the config file and plugins

**Comment by ZenergyBryson** [comment]
I really appreciate it - this is awesome, by the way.
I did have a question about the agents - I don't ever see them spinning up in ECS.  There's a task definition for them, but I don't see any Tasks run.  (I've only run the example so far, figuring out some other stuff before I put any workloads on it)

**Comment by ZenergyBryson** [comment]
Disregard the bit about the agents not showing up - they're just too fast!  I see them in the logs.
